# Generated by Django 5.0.6 on 2024-07-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
