# Generated by Django 5.0.6 on 2024-06-07 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_post_likes_thread_likes_alter_thread_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_read',
            field=models.ManyToManyField(blank=True, related_name='read_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
