# Generated by Django 5.0.6 on 2024-07-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_chatroom_chatroomuser_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
