# Generated by Django 5.0.6 on 2024-07-22 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_coursecontent_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='is_seen',
            field=models.ManyToManyField(blank=True, related_name='seen_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
