# Generated by Django 5.0.6 on 2024-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_coursecontent_content_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
