# Generated by Django 5.0.6 on 2024-05-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
