# Generated by Django 5.0.6 on 2024-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_event_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
