# Generated by Django 5.0.6 on 2024-07-23 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_coursecontent_is_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseannouncement',
            name='is_seen',
            field=models.ManyToManyField(blank=True, related_name='seen_announcement', to=settings.AUTH_USER_MODEL),
        ),
    ]
